#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./shellib/shellib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/shellib/shellib.sh"

# Install dependencies
function install_dependencies() {
    pkgs install 'apt:git' 'apt:python3-pip' 'pip:pre-commit' 'pip:gitlint' 'apt:npm' 'npm:markdownlint-cli' \
        'pip:yamllint' 'snap:shfmt' 'snap:shellcheck' 'apt:bats'
}

# Skip execution under test
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    install_dependencies
fi
