#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./lib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"

# Check there are not todos present
check_todos() {
    local todo='todo'
    local todos
    todos=$(grep -riI --exclude-dir={'.*','bats-*'} "#\\s*$todo" || true)

    if [ -z "$todos" ]; then
        out "No todos detected"
    else
        err "Anti-todo sanitization failed, todos:"
        echo "$todos" 1>&2
        return "$status_err"
    fi
}

# Skip functions execution if under test
if [ -z "${TEST+x}" ]; then
    check_todos
fi
