#!/usr/bin/env bash
set -e
set -o pipefail
set -u

LANG=C

# shellcheck disable=SC2034
ECHO_PRE_OK="$0 ✓"
# shellcheck disable=SC2034
ECHO_PRE_INST="$0 +"
# shellcheck disable=SC2034
ECHO_PRE_ERR="$0 ❌"

# Pre-push git hook

# Check local sanity
# Check for uncommitted changes
GIT_UNCOMMITED=$(git ls-files -dmo --exclude-standard)
if [ -n "$GIT_UNCOMMITED" ]; then
    echo "$ECHO_PRE_ERR git unstaged changes"
    exit 1
fi
echo "$ECHO_PRE_OK git unstaged changes"

# Check general sanity
scripts/check-sanity

# Check full codebase
# Workaround for https://gitlab.com/devopshq/gitlab-ci-linter/-/issues/3
if [ -z "${GL_TOKEN:-}" ]; then
    SKIP=gitlab-ci-linter pre-commit run -a
else
    export GITLAB_PRIVATE_TOKEN="$GL_TOKEN"
    pre-commit run -a
fi

# Run reduced test set
bats tests
echo "$ECHO_PRE_OK Reduced test set"
