#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./lib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"

# Check for unstaged changes
function check_unstaged() {
    local git_unstaged
    git_unstaged=$(git ls-files -dmo --exclude-standard)

    if [ -n "$git_unstaged" ]; then
        err "git unstaged changes detected"
        return "$status_err"
    fi
    out "git unstaged changes"
}

# Check full codebase
function run_pre-commit() {
    # Skip GitLab CI Linter if GitLab Personal Access Token is not set
    if [ -z "${GL_TOKEN:-}" ]; then
        SKIP=gitlab-ci-linter pre-commit run --hook-stage push
    else
        export GITLAB_PRIVATE_TOKEN="$GL_TOKEN"
        pre-commit run --hook-stage push
    fi
}

# Run reduced test set
function run_tests() {
    if bats tests; then
        out "Reduced test set"
    else
        err "Reduced test set failed"
        return "$status_err"
    fi
}

# Skip functions execution if under test
if [ -z "${TEST+x}" ]; then
    check_unstaged
    run_pre-commit
    scripts/check-sanity
    run_tests
fi
