#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
LANG=C

# shellcheck source=./lib.sh
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"

# Check codebase changes
function run_pre-commit() {
    # Skip GitLab CI Linter if GitLab Personal Access Token is not set
    if [ -z "${GL_TOKEN:-}" ]; then
        SKIP=gitlab-ci-linter pre-commit
    else
        export GITLAB_PRIVATE_TOKEN="$GL_TOKEN"
        pre-commit
    fi
}

# Run quick test set
function run_tests() {
    if bats tests; then
        out "Quick test set"
    else
        err "Quick test set failed"
        return "$status_err"
    fi
}

# Skip functions execution under test
if [ -z "${UNDER_TEST+x}" ]; then
    run_pre-commit
    run_tests
fi
