#!/usr/bin/env bash
set -e
set -o pipefail
set -u

LANG=C

# shellcheck disable=SC2034
ECHO_PRE_OK="$0 ✓"
# shellcheck disable=SC2034
ECHO_PRE_INST="$0 +"
# shellcheck disable=SC2034
ECHO_PRE_ERR="$0 ❌"

# Check sanity
# Check for todos
TODO="todo"
TODOS=$(grep -ri "#$TODO" || true)

if [ -n "$TODOS" ]; then
    echo "$ECHO_PRE_ERR todos sanitization failed:"
    echo "$TODOS"
    exit 1
else
    echo "$ECHO_PRE_OK todos sanitization"
fi
