#!/usr/bin/env bash
set -e
set -o pipefail
set -u

LANG=C

# shellcheck disable=SC2034
ECHO_PRE_OK="$0 ✓"
# shellcheck disable=SC2034
ECHO_PRE_INST="$0 +"
# shellcheck disable=SC2034
ECHO_PRE_ERR="$0 ❌"

# Pre-push git hook

# Check local sanity
# Check for uncommited changes
GIT_UNCOMMITED=$(git ls-files -dmo --exclude-standard)
if [ -n "$GIT_UNCOMMITED" ]; then
    echo "$ECHO_PRE_ERR git unstaged changes"
    exit 1
fi
echo "$ECHO_PRE_OK git unstaged changes"

# Check general sanity
tools/check-sanity

# Check full codebase
pre-commit run --all-files

# Run reduced test set
echo "$ECHO_PRE_OK Reduced test set"
