#!/usr/bin/env bash
set -e
set -o pipefail
set -u

LANG=C

# shellcheck disable=SC2034
ECHO_PRE_OK="$0 ✓"
# shellcheck disable=SC2034
ECHO_PRE_INST="$0 +"
# shellcheck disable=SC2034
ECHO_PRE_ERR="$0 ❌"

# Pre-commit git hook

# Normalize

# Check codebase changes
# Workaround for https://gitlab.com/devopshq/gitlab-ci-linter/-/issues/3
if [ -z "${GL_TOKEN:-}" ]; then
    SKIP=gitlab-ci-linter pre-commit
else
    export GITLAB_PRIVATE_TOKEN="$GL_TOKEN"
    pre-commit
fi

# Run quick test set
echo "$ECHO_PRE_OK Quick test set"
