#!/usr/bin/env bash
set -e
set -o pipefail
set -u

LANG=C

# shellcheck disable=SC2034
ECHO_PRE_OK="$0 ✓"
# shellcheck disable=SC2034
ECHO_PRE_INST="$0 +"
# shellcheck disable=SC2034
ECHO_PRE_ERR="$0 ❌"

# Setup repository
if [[ "$EUID" -eq "0" ]]; then
    # Do not run as a superuser
    echo >&2 echo "Superpowers might be more harmful than useful. Please run as a regular user."
    exit 1
else
    # Check pip is installed
    if pip3 -V >/dev/null; then
        echo "$ECHO_PRE_OK pip is installed"
    else
        echo "$ECHO_PRE_ERR pip is NOT installed"
        exit 1
    fi

    # Check npm is installed
    if npm -v >/dev/null; then
        echo "$ECHO_PRE_OK npm is installed"
    else
        echo "$ECHO_PRE_ERR npm is NOT installed"
        exit 1
    fi

    # Install pre-commit if it's not present
    if pip3 list | grep "^pre-commit\\s.*$" >/dev/null; then
        echo "$ECHO_PRE_OK pre-commit is installed"
    else
        if pip3 install pre-commit; then
            echo "$ECHO_PRE_INST pre-commit has been installed"
        else
            echo "$ECHO_PRE_ERR pre-commit installation failed."
            exit 1
        fi
    fi

    # Install gitlint if it's not present
    if pip3 list | grep "^gitlint\\s.*$" >/dev/null; then
        echo "$ECHO_PRE_OK gitlint is installed"
    else
        if pip3 install gitlint; then
            echo "$ECHO_PRE_INST gitlint has been installed"
        else
            echo "$ECHO_PRE_ERR gitlint installation failed."
            exit 1
        fi
    fi

    # Install markdownlint-cli if it's not present
    set +o pipefail
    if npm list -g 2>/dev/null | grep "markdownlint-cli" >/dev/null; then
        echo "$ECHO_PRE_OK markdownlint-cli is installed"
    else
        if $SUDO npm install -g markdownlint-cli; then
            echo "$ECHO_PRE_INST markdownlint-cli has been installed"
        else
            echo "$ECHO_PRE_ERR markdownlint-cli installation failed."
            exit 1
        fi
    fi
    set -o pipefail

    # Install yamllint if it's not present
    if pip3 list | grep "^yamllint\\s.*$" >/dev/null; then
        echo "$ECHO_PRE_OK yamllint is installed"
    else
        if pip3 install yamllint; then
            echo "$ECHO_PRE_INST yamllint has been installed"
        else
            echo "$ECHO_PRE_ERR yamllint installation failed."
            exit 1
        fi
    fi

    # Install pre-commit and gitlint into git hooks
    pre-commit install
    gitlint install-hook
fi
